### ISSUE TITLE
Exercice "Le dernier angle d’un triangle"

### ISSUE THREAD

**Issue by GaoTamanrasset** [AllanBlanchard/tutoriel_wp#15]
Bonjour et merci pour ce tutoriel très complet.
Je m'interroge sur l'exercice "Le dernier angle d’un triangle" au §3.1.4.5.
Si l'angle calculé respecte les mêmes priorités que les 2 angles en paramètres, c'est-à-dire être compris en 0 et 180 degrés, alors il n'est pas possible de prouver cette dernière propriété sans l'ajout d'une précondition qui est : first + second < 180 

Peut-être que la solution devrait plutôt être : 
```
/*@
    requires 0 <= a <= 180 ;
    requires 0 <= b <= 180 ;
    requires a + b < 180 ;

    ensures \result + a + b == 180 ;
    ensures 0 <= \result <= 180 ;
*/
int last_tri(int a, int b){
    return 180 - a - b;
}
```

Qu'en pensez-vous ? Ai-je mal compris l'exercice ?
Bonne journée

**Comment by AllanBlanchard** [comment]
Bonjour,

Désolé pour le retard de réponse, il faut vraiment que je fasse quelque chose pour mes notifications GitHub ...

C'est vrai que la version que j'ai mis en correction est simpliste. J'aime bien ta correction. Je vais la changer maintenant. Mais je laisse l'issue ouverte histoire de mettre un paragraphe plus précis dans l'explication de l'exercice quand je rédigerais la nouvelle version. 

Merci !

**Comment by GaoTamanrasset** [comment]
> EDIT: juste pour être tout à fait cohérent a + b <= 180

oui :)

Pas de soucis pour le retard. 
J'ai vu quelques erreurs de typo (dans le tutoriel en français), je vais les centraliser dans un mail quand j'ai 5 minutes.
Encore une fois, merci pour ce tutoriel.

**Comment by AllanBlanchard** [comment]
Top ! Merci !

**Comment by AllanBlanchard** [comment]
Ok, corrigé. Merci.
