### ISSUE TITLE
Quelques coquilles

### ISSUE THREAD

**Issue by GaoTamanrasset** [AllanBlanchard/tutoriel_wp#16]
Bonjour,

Voilà les quelques questions ou remarques sur le document :

1. 
https://github.com/AllanBlanchard/tutoriel_wp/blob/ab0b3b7f05c75d216a844ea1778bf7673f662f76/french/statements/function-calls.tex#L66

Est-ce que ce ne devrait pas plutôt être "*a **+ 1** au label L2" ?

2. 
https://github.com/AllanBlanchard/tutoriel_wp/blob/master/french/acsl-properties/lemmas.tex#L154

"au sens que chaque élément **soit** plus ..."

3. 
https://github.com/AllanBlanchard/tutoriel_wp/blob/master/french/acsl-logic-definitions.tex#L12

"ces 3 notions" ou "2 définitions", peut-être.

4. 
https://github.com/AllanBlanchard/tutoriel_wp/blob/master/french/proof-methodologies/lemma-functions.tex#L515

Répétition de "la plupart du temps" mais c'est un détail.

J'avais d'autres remarques plus importantes mais je me suis rendu compte qu'elles étaient déjà prises en compte sur git !

**Comment by AllanBlanchard** [comment]
> Est-ce que ce ne devrait pas plutôt être "*a + 1 au label L2" ?

Non, c'est bien `*a` (qui est égal à `\at(*a, L1)+1`, mais c'est pas forcément ce que je cherche à illustrer à ce point de l'explication).

Merci pour les typos, c'est corrigé dans la branche de la prochaine version.

**Comment by GaoTamanrasset** [comment]
> Non, c'est bien *a (qui est égal à \at(*a, L1)+1, mais c'est pas forcément ce que je cherche à illustrer à ce point de l'explication).

Oups, en effet, c'est clair quand on prend le temps de bien lire. :)

**Comment by AllanBlanchard** [comment]
Tout est corrigé à la fois dans la branche de prochaine version et sur le brouillon ZDS.

Merci :)
