### ISSUE TITLE
Exercise 4.1.6.2. Empty “then” branch in conditional

### ISSUE THREAD

**Issue by TrigDevelopment** [AllanBlanchard/tutoriel_wp#17]
Hello and thank you for the great tutorial!

In the second paragraph of Exercise 4.1.6.2. Empty “then” branch in conditional:
"Show that when, instead of the “else” branch, the “then” branch is empty, the conjunction of
the condition and the precondition must implies the postcondition of the “else” branch."

I think that this is typo but I'm not sure how to fix it. Do you mean "conjunction of
the *negation* of condition and precondition must *imply* the postcondition of the “else” branch."?

**Comment by AllanBlanchard** [comment]
> Hello and thank you for the great tutorial!

You're welcome :)

> I think that this is typo but I'm not sure how to fix it. Do you mean "conjunction of
> the negation of condition and precondition must imply the postcondition of the “else” branch."?

There is indeed a typo (imply/implies), but there is no problem with "the conjunction of the condition and the precondition". The "else" branch contains code, thus from the precondition and the negation of the condition, it will establish a new postcondition (probably modifying the memory state), as the "then" branch is empty, it means that the conjunction of the precondition and the condition must already imply this postcondition.

However, I should probably rephrase that. I keep this issue open for the next version.

Thank you !

**Comment by AllanBlanchard** [comment]
Fixed, thank you :)
