### ISSUE TITLE
Exercise 7.3.6.1: additionnal assert needed to prove post-condition

### ISSUE THREAD

**Issue by qsantos** [AllanBlanchard/tutoriel_wp#29]
Using the code from the [correction of 7.3.6.1](https://github.com/AllanBlanchard/tutoriel_wp/blob/master/code/proof-methodologies/lemma-functions/ex-1-sum-of-n-integers-answer.c) in Frama-C 21 Scandium, WP fails to prove the post-condition of `sum_n` with either Alt-Ergo or CVC4. Somehow, adding `//@ assert 0 <= n * (n + 1);` allows either to prove it.

**Comment by AllanBlanchard** [comment]
I think that there is a small regression in WP, I'll had the assertion for now, but I will also have a look to WP.

**Comment by AllanBlanchard** [comment]
Issue is fixed on master.

**Comment by qsantos** [comment]
Thanks for the promptness of your reply!

**Comment by AllanBlanchard** [comment]
Note, just for fun : using -warn-unsigned-overflow provide the assertion so that the bug is hidden ^^

**Comment by qsantos** [comment]
Oh, right. I turned it off for some of the exercises of chapter 7 and must have forgotten to turn it back on. By the way, thanks a lot for your manual. It's a gem!
