### ISSUE TITLE
generate pdf

### ISSUE THREAD

**Issue by jensgerlach** [AllanBlanchard/tutoriel_wp#3]
Do you have a script to generate latex or pdf?

**Comment by AllanBlanchard** [comment]
Currently, I don't and most of the task is done manually. But I plan to create such a script. Basically, I can generate a TeX version with pandoc but then I still have to replace pathes to images, transforms the special markdown blocks used by ZesteDeSavoir and change some values to general format of the PDF.

**Comment by maroneze** [comment]
Before you create the script, you could add the commands you use to do it, so that some copy-pasting could help reproducing (at least partially) the PDF.

**Comment by AllanBlanchard** [comment]
In fact, currently it requires a particular tool that was on Zeste de Savoir and I think that it is not available anymore (I still have it but I do not exactly remember what are all the dependencies). 

Honestly I do not like this situation at all, and I think that I will convert everything to TeX in the weeks to come. It will be painful but it will save a lot of time later.

**Comment by jensgerlach** [comment]
Working with markdown was an interesting experience for me.
In the long run, however, it looks like as if latex is still the better investment.

**Comment by AllanBlanchard** [comment]
The Makefile should now do the job.
