### ISSUE TITLE
Question about order3

### ISSUE THREAD

**Issue by pdietl** [AllanBlanchard/tutoriel_wp#42]
is not 
https://github.com/AllanBlanchard/tutoriel_wp/blob/f4c1be54e6b2a315836cc125ce7f0ed5f24b2afc/code/function-contract/well-specified/ex-5-order-3-answer.c#L10

implied by https://github.com/AllanBlanchard/tutoriel_wp/blob/f4c1be54e6b2a315836cc125ce7f0ed5f24b2afc/code/function-contract/well-specified/ex-5-order-3-answer.c#L8

**Comment by AllanBlanchard** [comment]
Indeed, it is. I'll remove the additional property in the next version.

Thanks!

**Comment by AllanBlanchard** [comment]
Merged in next version
