### ISSUE TITLE
Small typo in chapter 3 of the English version (page 29 in the PDF)

### ISSUE THREAD

**Issue by nicolaioestergaard** [AllanBlanchard/tutoriel_wp#49]
Hi,
While reading through your tutorial I spotted a small typo in this section:

https://github.com/AllanBlanchard/tutoriel_wp/blob/25ac4605307f1b12f4a7413dbd71f3e4c6f5cdd2/english/function-contract/contract.tex#LL372-L374C14

Currently it says:

"This is the verification condition generated by WP about our property and our
program, we do need to understand everything here, but we can get the
general idea."

But it should properly be this instead:

"This is the verification condition generated by WP about our property and our
program, we do __not__ need to understand everything here, but we can get the
general idea."

**Comment by AllanBlanchard** [comment]
Thanks! I add this my todos.

**Comment by AllanBlanchard** [comment]
Fixed in 0ecdb86ad5a1950a90eb3443cfbac01d8e7f6346
