### ISSUE TITLE
\begin{zdsalertblock} without {}

### ISSUE THREAD

**Issue by maroneze** [AllanBlanchard/tutoriel_wp#5]
In the English version, this block is showing with title "P" and text "lease note...":

    \begin{zdsalertblock}
      Please note that this document is the very first english version of the
      tutorial...

I think there's a `{}` missing after `\begin{zdsalertblock}` to prevent it from happening.

**Comment by AllanBlanchard** [comment]
Yes, I forgot it, thank you.

**Comment by AllanBlanchard** [comment]
Fixed
