### ISSUE TITLE
Différentes typos repérées

### ISSUE THREAD

**Issue by Artalik** [AllanBlanchard/tutoriel_wp#56]
Voici les petites typos que je pense avoir relevées dans la version française :

https://github.com/AllanBlanchard/tutoriel_wp/blob/ec0d0cbc17426c9a9d7c4c2fb13859474773d990/french/function-contract/contract.tex#L414-L415

Je trouve le "pas incapables" suspicieux...

https://github.com/AllanBlanchard/tutoriel_wp/blob/ec0d0cbc17426c9a9d7c4c2fb13859474773d990/french/function-contract/well-specified.tex#L355

https://github.com/AllanBlanchard/tutoriel_wp/blob/ec0d0cbc17426c9a9d7c4c2fb13859474773d990/french/function-contract/well-specified.tex#L381

Je crois que "bord" ne prend pas de "s".

https://github.com/AllanBlanchard/tutoriel_wp/blob/ec0d0cbc17426c9a9d7c4c2fb13859474773d990/french/proof-methodologies/lemma-functions.tex#L219

"que nous obtenir" -> obtenons

https://github.com/AllanBlanchard/tutoriel_wp/blob/ec0d0cbc17426c9a9d7c4c2fb13859474773d990/french/proof-methodologies/lemma-functions.tex#L275-L276

Elle ne retourne pas -1 mais SIZE_MAX d'après le code du dépot et UINT_MAX d'après l'ancien pdf.

**Comment by AllanBlanchard** [comment]
C'est fixé, merci
