### ISSUE TITLE
ACSL by Example

### ISSUE THREAD

**Issue by jensgerlach** [AllanBlanchard/tutoriel_wp#7]
In the the tutorial "ACSL by Example" mentioned but, unfortunately, with the old URL at Fraunhofer FOKUS.

Please link directly to    https://github.com/fraunhoferfokus/acsl-by-example

**Comment by AllanBlanchard** [comment]
I thought that the URL at Fraunhofer FOKUS was still up to date, I should have verified, sorry. Now it is fixed :) . Thanks @jensgerlach!
